# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_spacelaser_wrappers", use_symbols = TRUE, package_name = "spacelaser")

#' @docType package
#' @usage NULL
#' @useDynLib spacelaser, .registration = TRUE
NULL

rust_read_gedi <- function(url, product, xmin, ymin, xmax, ymax, columns, beams, bearer_token) {
  .Call("wrap__rust_read_gedi", url, product, xmin, ymin, xmax, ymax, columns, beams, bearer_token)
}

rust_read_icesat2 <- function(url, product, xmin, ymin, xmax, ymax, columns, tracks, bearer_token) {
  .Call("wrap__rust_read_icesat2", url, product, xmin, ymin, xmax, ymax, columns, tracks, bearer_token)
}

rust_hdf5_groups <- function(url, path, bearer_token) {
  .Call("wrap__rust_hdf5_groups", url, path, bearer_token)
}

rust_hdf5_dataset <- function(url, dataset_path, bearer_token) {
  .Call("wrap__rust_hdf5_dataset", url, dataset_path, bearer_token)
}
